sources := "src/*.cpp src/bytecode/*.cpp" 
headers := "src/*.h src/bytecode/*.h"
format:
	clang-format -i --style=Google {{sources}} {{headers}}

tidy : format
	clang-tidy --checks='clang-analyzer-*, performance-*, bugprone-*' {{sources}}

build: format 
	clang {{sources}} -std=c++23 -g -Werror -Wall -Wextra -pedantic-errors -Wconversion -Wsign-conversion -fsanitize=address -lSDL3 -o ../out/debug.bin

run:
	../out/debug.bin
